### ISSUE TITLE
Device Model showing wrong number

### ISSUE THREAD

**Issue by ghost** [nullpixel/tsssaver#11]
**iPhone 6S** , **N71AP**
original model number is **iPhone 8,1**
but
showing as **iPhone 10,6**

**Comment by AppleBetas** [comment]
Are you using any tweak that simulates the iPhone X experience and UI?

**Comment by nullpixel** [comment]
The tweak by Andy Wiik that does this actually hooks sysctl, which is how I get the model number.

**Comment by ghost** [comment]
Yes, LittleX

**Comment by nullpixel** [comment]
That’s a LittleX issue. If you can, disable it for the TSSsaver app.
