### ISSUE TITLE
Crashing on launch - SIGKILL CODESIGNING

### ISSUE THREAD

**Issue by ringosham** [nullpixel/tsssaver#12]
iPad mini 2 - iOS 10.3.1
Crashlog available here, and it doesn't seem like a tweak conflict.
[TSSSaver-2018-03-04-020548.zip](https://github.com/nullpixel/tsssaver/files/1778590/TSSSaver-2018-03-04-020548.zip)

**Comment by nullpixel** [comment]
Thanks a **lot**! Someone who actually has crash logs :) 

I can look into this now. Are you on g0blin?

**Comment by ringosham** [comment]
It was doubleH3lix RC3 at the time of the original post. I'll update to RC6 to see if problem persists.

**Comment by ringosham** [comment]
Yup, the problem lies in doubleH3lix. I updated to RC6 and the crash is gone.
I felt kind of stupid after finding the cause of it.....

**Comment by nullpixel** [comment]
not your fault! I got so many messages about this, and I did get this issue myself once. thanks for letting me know anyway.
