### ISSUE TITLE
instant crash after opening

### ISSUE THREAD

**Issue by liuxuan30** [nullpixel/tsssaver#13]
Hi nullpixel,

Just add your source on cydia on Electra 1.0.2; seeing downloading libswift4 and tsssaver, however, it will crash immediately once I open it.

Any idea?

**Comment by liuxuan30** [comment]
managed to capture one log:
>kernel(AppleMobileFileIntegrity)[0] <Error>: Library Validation failed: Rejecting '/usr/lib/libswift/4.0.3/libswiftCore.dylib' (Team ID: V9AUD2URP3, platform: no) for process 'TSSSaver(1105)' (Team ID: none, platform: no), reason: mapping process has no Team ID and is not a platform binary

seems both libswift4 and the tssaver itself is not platform-ized. How to fix it? re-sign with entitlement by jtool? or you could fix and update?

**Comment by nullpixel** [comment]
They’re platformized. I believe the fix is to install tweak injector

**Comment by liuxuan30** [comment]
thanks. Will try.

**Comment by liuxuan30** [comment]
May I ask one more question. What's the purpose of tweak injector?
Since the binary has platform entitlement already, why crash still?

**Comment by nullpixel** [comment]
Not a clue
