### ISSUE TITLE
A12 support?

### ISSUE THREAD

**Issue by Macleykun** [nullpixel/tsssaver#16]
Hi,

I was wondering if support for A12 devices would be possible for the tsssaver app.

I enjoy using tsssaver and it's handy application form :-)

**Comment by nullpixel** [comment]
It’s not possible at the moment because of changes Apple made to saving nonces on A12. I’ll have a look at it when I can.

**Comment by Macleykun** [comment]
Hey sorry for the late reply!
Thank you for atleast considering my suggestion, i do wanna suggest maybe the following (temporarly) solution for this:
When the device is A12(X), users should manually specify their nonce from [this tutorial](https://www.reddit.com/r/jailbreak/comments/apjwhy/tutorial_new_tutorial_for_saving_shsh2_blobs_on/). The app can then remember this nonce.
The user only has to open the app and click on save blobs!

Hope the above is something useful for you.

**Comment by Macleykun** [comment]
Hey dude, was wondering if my temporarly suggestion could help you out in the short-term!

**Comment by Macleykun** [comment]
Hey dude, I was wondering if you wanna react to my suggestion. ^^

**Comment by nullpixel** [comment]
Sorry, I’ve been extremely busy lately and I’ll get around to this when I next work on the app

**Comment by Macleykun** [comment]
Sure no problem! I'm happy your still ok considering implementing this suggestion!

Take care and enjoy your work!

**Comment by Macleykun** [comment]
Heya, was wondering how things were going at your side ^^

**Comment by nullpixel** [comment]
Same as before.

**Comment by Macleykun** [comment]
Np!
Van: nullpixel
Verzonden: dinsdag 13 augustus 2019 21:47
Aan: nullpixel/tsssaver
CC: Macley; Author
Onderwerp: Re: [nullpixel/tsssaver] A12 support? (#16)

Same as before.

**Comment by Macleykun** [comment]
I've chosen to use this instead, it's also opensource so you can look it up and see it for yourself!
I've already tested this with A12 to 12.4, actually worked beter then TSSsaver!
https://github.com/Haifisch/MobileTSS

**Comment by nullpixel** [comment]
It’s a conscious decision to not save blobs like this. We do not want to manually allow the user to set the generator in the app because of UX, and I’ll think you’ll find blobs saved with that app won’t restore your device because of nonce entanglement.

**Comment by Macleykun** [comment]
Heya, sorry for the very late reply.
The app supports entering the generator and everything, it’s not done automatic but the blobs saves do restore!
Anyways, is there an update on this issue? Can it be closed?

**Comment by itspolly** [comment]
It's still a problem, but I think I've found a way of getting the generator on device. Just a matter of when I can get round to implementing it.

**Comment by Macleykun** [comment]
Sureo! Goodluck on it :) looking forward to it!

**Comment by Macleykun** [comment]
Hey @jamiebishop have ya been able to get around it?

**Comment by Macleykun** [comment]
Heya, any update on this issue :) ?
