### ISSUE TITLE
13.3 folder is empty

### ISSUE THREAD

**Issue by jebediah2** [nullpixel/tsssaver#18]
I grabbed the ApNonce of my A12 a while ago and recently used it to save 13.3 blobs on https://tsssaver.1conan.com but today I go online to fetch it and the folder is empty. Why is that?

**Comment by aydenp** [comment]
This seems to be an issue for the TSSSaver web service, not the iOS frontend for it.

**Comment by jebediah2** [comment]
There should be a public announcement about it. I wasn't warned and am now locked out of 13.3. Had I and other people known there are other tools available to secure your blobs such as [shsh.host](shsh.host)

**Comment by aydenp** [comment]
This would not be the proper place to voice your concerns, especially provided the app doesn’t support A12 or A13. I recommend reaching out to the developer of the TSS Saver website.

**Comment by jebediah2** [comment]
That is correct.

**Comment by nullpixel** [comment]
Yeah, this isn’t the place to report issues with the website. Although, I am interested — how did you get the app to work with A12/13, when it doesn’t support it?

**Comment by jebediah2** [comment]
I didn't. I thought there was a direct relation between your app and the web service that started at [https://github.com/TSSSaver/TSSSaver](https://github.com/TSSSaver/TSSSaver), and since the latter is archived and that I didn't get a response from [u/1Conan](https://www.reddit.com/user/1Conan/), I posted here.
This being said I do suggest you double check that all 13.3 are fetched up to A11, as it might not just be A12-centric, but yeah I'll move the discussion somewhere else.

**Comment by aydenp** [comment]
This issue is that we don't have control over the web service. This repo and its maintainers are in charge of the app only.

**Comment by Hamlock-Maneuver** [comment]
Jebediah2 is a dipshit.  He doesn't have a clue what he is doing and won't listen to correct information.  He is a lost cause not worthy of any attention.
