### ISSUE TITLE
Add conflict with iOS 7 in cydia

### ISSUE THREAD

**Issue by dioni21** [nullpixel/tsssaver#8]
I'm trying to run TSSsaver in an old iPhone 4s still on iOS 7.1.2, but it simply exits after starting. Apparently it is requesting some inexistent library function: _OBJC_CLASS_$_UIAlertAction

**Comment by nullpixel** [comment]
The app currently does not support iOS 7 as it uses newer apis, such as UIAlertAction.

**Comment by dioni21** [comment]
Is it possible, then, to inform this to cydia?

I know it is possible, but don't know how, sorry...

**Comment by nullpixel** [comment]
I thought I did add this, apologies. I will look into fixing this.

**Comment by dioni21** [comment]
Tks.   I will monitor this issue and send feedback as soon as you update on cydia.
